languageCode = "ja-jp"
title = "Blog"
baseurl = "http://blog.70-10.net"
googleAnalytics = "UA-99979822-1"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[author]
  name = "70_10"

[params]
  twitter = "70_10"
  github = "70-10"
