languageCode = "ja-jp"
title = "MNML"
baseurl = "https://blog.70-10.net"
googleAnalytics = "UA-99979822-1"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[author]
  name = "70_10"

[params]
  twitter = "70_10"
  github = "70-10"

[taxonomies]
  tag = "tags"

[outputs]
home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
