languageCode = "ja-jp"
title = "blog.70-10.net"
baseurl = "https://blog.70-10.net"
googleAnalytics = "UA-99979822-1"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[author]
  name = "70_10"

[params]
  twitter = "70_10"
  github = "70-10"

[taxonomies]
  tag = "tags"
