[build]
publish = "public"
command = "npm install;hugo version;hugo"

[context.production.environment]
HUGO_VERSION = "0.46"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm install;hugo version;hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.46"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm install;hugo version;hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.46"

[context.branch-deploy]
command = "npm install;hugo version;hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.46"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
