version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.26
    working_directory: /blog
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Git: Setup"
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 'circleci@cureapp.jp'
      - run:
          name: "Hugo: Build"
          command: hugo
      - run:
          name: "Git: Checkout public"
          command: git checkout -t origin/gh-pages
      - run:
          name: "Git: Remove old files"
          command: |
            git rm $(git ls-files | grep -v "CNAME")
      - run:
          name: mv public
          command: |
            mv public/* .
            rm -rf public
      - run:
          name: "Git: Push"
          command: |
            git add -A
            git commit -m "release at $(date +'%Y.%m.%d %H:%M:%S') [ci skip]" --allow-empty
            git branch -vv
            git push -u origin gh-pages
