name: Build and preview

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 20.x

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use pnpm@8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install
        run: |
          pnpm install --frozen-lockfile
      - name: Check pnpm-lock.yaml
        run: git diff --exit-code pnpm-lock.yaml
      - name: Lint
        run: |
          pnpm lint
      - name: Build
        run: |
          pnpm build
        env:
          NODE_ENV: preview
      - name: Publish preview
        id: preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Comment preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Preview URL: ${{ steps.preview.outputs.NETLIFY_URL }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
