name: Build and preview

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build
        env:
          GATSBY_SPACE_ID: ${{ secrets.GATSBY_SPACE_ID }}
          GATSBY_ACCESS_TOKEN: ${{ secrets.GATSBY_ACCESS_TOKEN }}
      - name: Publish preview
        id: preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Comment preview URL
        uses: thollander/actions-comment-pull-request@master
        with:
          message: "Preview URL: ${{ steps.preview.outputs.NETLIFY_URL }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
